// Generated by scripts/optimize-images.mjs — do not edit by hand.
// Re-run: npm run optimize-images

export type ImageMeta = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

const LEGACY_SRC: Record<string, string> = {
  "/images/crm-source.png": "/images/crm.webp",
  "/images/chesterbrook-source.png": "/images/chesterbrook.webp",
  "/images/zoneiq-source.png": "/images/zoneiq.webp",
  "/images/exp-rally.png": "/images/exp-rally.webp",
  "/images/nhs-drive.png": "/images/nhs-drive.webp",
  "/images/boat-engine.png": "/images/boat-engine.webp",
  "/images/water-polo-action.png": "/images/water-polo-action.webp",
  "/images/oddz-oyster-source.png": "/images/oddz-oyster.webp",
  "/images/oddz-track-source.png": "/images/oddz-track.webp",
  "/images/home-presenting.png": "/images/home-presenting.webp",
  "/images/profile.jpg": "/images/profile.webp",
  "/images/home-1.png": "/images/home-1.webp",
  "/images/home-2.png": "/images/home-2.webp",
  "/images/home-3.png": "/images/home-3.webp",
  "/images/home-4.png": "/images/home-4.webp",
  "/images/housefly.png": "/images/housefly.webp",
  "/images/swim-instructor.png": "/images/swim-instructor.webp",
  "/images/water-polo-team.png": "/images/water-polo-team.webp",
  "/images/boat-on-water.png": "/images/boat-on-water.webp",
  "/images/surfing-board.png": "/images/surfing-board.webp",
  "/images/spearfishing-beach.png": "/images/spearfishing-beach.webp",
  "/images/spearfishing-ocean.png": "/images/spearfishing-ocean.webp",
};

export const imageMeta: Record<string, ImageMeta> = {
  "/images/crm.webp": {
    src: "/images/crm.webp",
    width: 1024,
    height: 566,
    blurDataURL:
      "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACQAQCdASoKAAoAA4BaJZwAAudZVcAA/vYkL76rh1RT5ws8AAA=",
  },
  "/images/chesterbrook.webp": {
    src: "/images/chesterbrook.webp",
    width: 1024,
    height: 683,
    blurDataURL:
      "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAAAwAQCdASoKAAoAA4BaJQAAbgAA/u98k8WSa+f7UU/eh4knTv2WrRqAAAA=",
  },
  "/images/zoneiq.webp": {
    src: "/images/zoneiq.webp",
    width: 960,
    height: 640,
    blurDataURL:
      "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoKAAoAA4BaJZQC7AELVta8qsgA/vYyFHCbFuSdNf6ue31HiqGHx7V+Q9L77btQ2boFd4pNTznFAcAA",
  },
  "/images/exp-rally.webp": {
    src: "/images/exp-rally.webp",
    width: 576,
    height: 384,
    blurDataURL:
      "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoKAAoAA4BaJagCdAD1eaO4rMgAzjMHgNSe7cc8BjHH7BRKhe97aCjOPa0geIC5zbmQCqgWF6b6U0uBIcZ0Zm9fwaR8AAAA",
  },
  "/images/exp-rally-vertical.webp": {
    src: "/images/exp-rally-vertical.webp",
    width: 576,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoKAAoAA4BaJQBOgBwwn+VU5gAA+N/5vysd/tQPxs48uMr/YQZr0EMMrsT+q+xmVB2NScXmfwaw2AQQbya3zf90CgZuR376gAA=",
  },
  "/images/nhs-drive.webp": {
    src: "/images/nhs-drive.webp",
    width: 816,
    height: 544,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoKAAoAA4BaJQBOgCFw4VY90DYAAMyjbI+WxL8St8ISkud17VPSqp0BR8uzXuzloThRAjTm8HKMYqyybhVxaQ51FQvYIOdtTRhOzgAA",
  },
  "/images/boat-engine.webp": {
    src: "/images/boat-engine.webp",
    width: 768,
    height: 512,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAQCdASoKAAoAA4BaJZQAAlESxUAA99uOmXS1M37CUGEW98gXKjuhRymRKrXH1dUccciLxeye83DADaVRgmIiWbuDQAAA",
  },
  "/images/water-polo-action.webp": {
    src: "/images/water-polo-action.webp",
    width: 1024,
    height: 683,
    blurDataURL:
      "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAQCdASoKAAoAA4BaJZACdADbVPAAzFS5kZWnI4OxGe+psVQm8ScXKaUgiLm/+gmQSGZlTnSIgAAA",
  },
  "/images/oddz-oyster.webp": {
    src: "/images/oddz-oyster.webp",
    width: 885,
    height: 590,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoKAAoAA4BaJZgCdAD5h/sqwAAA/vfxV56uhmgLHP4TEyosJxk5qcqV+ylJ1nZ679dQryxUtc68VwlLr34FHoUXAAA=",
  },
  "/images/oddz-track.webp": {
    src: "/images/oddz-track.webp",
    width: 575,
    height: 383,
    blurDataURL:
      "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoKAAoAA4BaJbACdH8AE74xwwsAAP55P0P+ACVgZJzua7NyrHq/1CgVne9mLLiPNHTNfNQ6CEvqSn+HdSO0FlsAAAA=",
  },
  "/images/home-presenting.webp": {
    src: "/images/home-presenting.webp",
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoKAAoAA4BaJYwCsAEekqi3XY4AAP6IUF5fI4XISOaafQnke0lgdS3eRisNYTSEIKJ/VXvlNDa2fvgajHfJD4/PGRUAAA==",
  },
  "/images/profile.webp": {
    src: "/images/profile.webp",
    width: 1200,
    height: 1391,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAgCdASoKAAoAA4BaJYwCdH8AFmVcCb5X/XMAAP7qiF473QBeSM2A7G7dRk4IjHXna4N0qsHRktctPBw7MbeIL0yZlydjj0UAAA==",
  },
  "/images/home-1.webp": {
    src: "/images/home-1.webp",
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoKAAoAA4BaJYgCdAD7FsK9TtzeAPjbiFFCvA4lqu5kX88havvsJEa5EK3lBBhLsZ8T5GBNwawDAL6x4efXfvPFiStYMz4AAAA=",
  },
  "/images/home-2.webp": {
    src: "/images/home-2.webp",
    width: 788,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoKAAoAA4BaJZACdADya84k4AD893BmnKvy70PlTY/jcTVbK27Q7Q4RCCeoTmTnjiCsZ1nIUSmkooir73c6/mwmP1qbvu1A0F1Io5t2m2WxyAAA",
  },
  "/images/home-3.webp": {
    src: "/images/home-3.webp",
    width: 713,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoKAAoAA4BaJYgCdEf/gbgvzx0AAP7kS/kx/1BT/0UfNspPGoY1jLiKYFYtw6mmVO1gy9VgyDyNgXYF9VlJ4JO4agAAAA==",
  },
  "/images/home-4.webp": {
    src: "/images/home-4.webp",
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoKAAoAA4BaJZQAAtyhixydgADxGchylziv8gu+MnimUNLpBYXNw0md8//LD00P59HVlPw5JThh55NUqFVYHzENdW9CAA==",
  },
  "/images/housefly.webp": {
    src: "/images/housefly.webp",
    width: 1024,
    height: 890,
    blurDataURL:
      "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoKAAoAA4BaJaACdADdjUlqHEAA/Tydmx4ud63L/tYCV8bDOKKhp6Np113vfMuXY36NiPTUs7Dj6AElPQmywtcGQ+YdJ7pUAAA=",
  },
  "/images/swim-instructor.webp": {
    src: "/images/swim-instructor.webp",
    width: 927,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoKAAoAA4BaJbACsAELhSYs9HwAAP3D1BHxSi+9OWNfMc4/ShNEhXGyl6VrTlNgau+swLQO5wHRHsjN+VRTAAAA",
  },
  "/images/water-polo-team.webp": {
    src: "/images/water-polo-team.webp",
    width: 1024,
    height: 942,
    blurDataURL:
      "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoKAAoAA4BaJZACdAEQzAC754AA8qRKTHE/Vr6Rjd8S6Tj2zp8hwWk6G9sD0pVYKKwy1SJO6oCE1gO+gR2mA9D67AAAAA==",
  },
  "/images/boat-on-water.webp": {
    src: "/images/boat-on-water.webp",
    width: 768,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoKAAoAA4BaJZACdADcHgdacQAA+mElZqm8JB6ge3McadJ0IF6aDofd7nCaF8pqnW9Qtqh1SaRszs8kPWsxgAAA",
  },
  "/images/surfing-board.webp": {
    src: "/images/surfing-board.webp",
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAQCdASoKAAoAA4BaJQAASxthzuUAAP6sdkRcNpvKMUR3GQwymufk37wOAsSxg5G4DTnKQ49D+3Qa/Ka2Zldofnm/lsldv3h1oJJpq0Q1sAAA",
  },
  "/images/spearfishing-beach.webp": {
    src: "/images/spearfishing-beach.webp",
    width: 1024,
    height: 768,
    blurDataURL:
      "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoKAAoAA4BaJZgCdEf/gcXvT/qYAAD82TrZPuuWBsFjtR9THcFCbfL/wzW+tSDWiNzGp3rXNlY8eMp3KGYlXwjqSvNlh31/NhOVBoDyE7Cs8gAA",
  },
  "/images/spearfishing-ocean.webp": {
    src: "/images/spearfishing-ocean.webp",
    width: 739,
    height: 1024,
    blurDataURL:
      "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoKAAoAA4BaJQBOgB6M0zoZUAD+w/EIk0BF7Is+MFTCNBk0eB6Ja2QEM8BdgAAA",
  },
};

export function getImageMeta(src: string): ImageMeta {
  const resolved = LEGACY_SRC[src] ?? src;
  const meta = imageMeta[resolved];
  if (!meta) {
    throw new Error(`Unknown image: ${src}`);
  }
  return meta;
}
